# fly.toml app configuration file generated for canna-bot on 2023-07-21T08:34:31-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "canna-bot"
primary_region = "yyz"

[env]
  BEST_DOTA_GUILD_ID = "761903068127428649"
  CHANNEL_ID_CHURCH_OF_RICO = "1113512037780303995"
  CHANNEL_ID_DOTA_2 = "798885243322499073"
  CHANNEL_ID_GENERAL = "773552279265083412"
  ROLE_ID_EVERYBODY_EXCEPT_DRABZ = "1062760837724512396"
  USER_ID_CANNA = "169619011238232073"
  USER_ID_RICO = "212986339212263434"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
